# Generated by Django 4.2 on 2023-04-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pici_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picihao', models.CharField(max_length=200)),
                ('pinpai', models.CharField(max_length=50)),
                ('shengchan_date', models.DateField()),
                ('kaibao_up_time', models.DateTimeField()),
                ('kaibao_down_time', models.DateTimeField()),
                ('kaibao_weight', models.CharField(max_length=20)),
                ('songsan_up_time', models.DateTimeField()),
                ('songsan_down_time', models.DateTimeField()),
                ('songsan_weight', models.CharField(max_length=20)),
                ('songsan_shuifen_value', models.CharField(max_length=20)),
                ('songsan_wendu_value', models.CharField(max_length=20)),
                ('songsan_rate', models.CharField(max_length=20)),
                ('jialiao_up_time', models.DateTimeField(default='')),
                ('jialiao_down_time', models.DateTimeField(default='')),
                ('jialiao_weight', models.CharField(default='', max_length=20)),
                ('jialiao_jingdu', models.CharField(default='', max_length=20)),
                ('jialiao_wendu_value', models.CharField(default='', max_length=20)),
                ('jialiao_shuifen_value', models.CharField(default='', max_length=20)),
                ('chugui_bianhao', models.CharField(default='', max_length=20)),
                ('jingui_kaishi_time', models.DateTimeField(default='')),
                ('jingui_jieshu_time', models.DateTimeField(default='')),
                ('chugui_kaishi_time', models.DateTimeField(default='')),
                ('chugui_jieshu_time', models.DateTimeField(default='')),
            ],
        ),
    ]
