# Generated by Django 4.2 on 2023-05-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chenben_test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chusilv_data', models.CharField(max_length=20)),
                ('huishouyansi_data', models.CharField(max_length=20)),
                ('danxianghaoye_data', models.CharField(max_length=20)),
                ('guochengxiaohao_data', models.CharField(max_length=20)),
                ('renyuanxiaohao_data', models.CharField(max_length=20)),
                ('nenghao_data', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
